name: AC/DC Countdown

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  run-shell-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run script
        env:
          discord_webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          TZ: "America/Sao_Paulo"
        run: |
          sudo chmod +x ./acdc.sh
          ./acdc.sh
